apiVersion: v1
kind: Service
metadata:
  name: test1
  namespace: namespace-workflow-1689835096550
spec:
  type: LoadBalancer
  selector:
    app: test1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000